"use client";

import { useState, useMemo, useRef, useEffect } from 'react';
import type { Participant } from '@/types';
import { Button } from '@/components/ui/button';
import { Header } from '@/components/layout/Header';
import { SlotMachine } from '@/components/raffle/SlotMachine';
import { SessionIndicator } from '@/components/raffle/SessionIndicator';
import { ParticipantsList } from '@/components/raffle/ParticipantsList';
import { secureRandom } from '@/lib/utils';
import { useToast } from '@/hooks/use-toast';
import { Trophy, ServerCrash } from 'lucide-react';
import { useParticipants } from '@/context/ParticipantsContext';
import { useSessionContext } from '@/context/SessionContext';
import { Confetti } from '@/components/raffle/Confetti';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import Image from 'next/image';
import { supabase } from '@/lib/supabase';

const initialLogo = PlaceHolderImages.find(img => img.id === 'mcp-logo');

export default function Home() {
  const {
    allParticipants,
    setAllParticipants,
    availableParticipants,
    setAvailableParticipants,
    loading,
    error,
    refetch
  } = useParticipants();

  const { sessionId } = useSessionContext();

  const [winner, setWinner] = useState<Participant | null>(null);
  const [isRaffling, setIsRaffling] = useState(false);
  const [spinHasEnded, setSpinHasEnded] = useState(false);
  const [isRainingLogos, setIsRainingLogos] = useState(false);
  const [logoUrl, setLogoUrl] = useState<string | undefined>(initialLogo?.imageUrl);
  const { toast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);
  // Supabase instance is imported globally if needed, or we can use the hook logic.
  // Actually, for this component we can just import the client directly.
  const handleParticipantsLoad = async (newParticipants: Participant[]) => {

    // Client-side filtering logic from original code
    const existingDisplayNames = new Set(allParticipants.map(p => p.display_name));
    const uniqueNew = newParticipants.filter(p => !existingDisplayNames.has(p.display_name));

    if (uniqueNew.length > 0) {
      if (!sessionId) {
        toast({
          title: "Session Error",
          description: "No active session. Please refresh the page.",
          variant: "destructive"
        });
        return;
      }

      try {
        // Map to the shape expected by Supabase, including session_id
        // Note: id is auto-generated by Supabase as UUID
        const participantsToInsert = uniqueNew.map(participant => ({
          name: participant.name,
          last_name: participant.last_name,
          display_name: participant.display_name,
          session_id: sessionId,
          email: participant.email,
        }));

        const { error } = await supabase.from('participants').insert(participantsToInsert);

        if (error) throw error;

        // Refresh participants list immediately
        await refetch();

        toast({
          title: "Participants Added",
          description: `${uniqueNew.length} new participants added to session ${sessionId?.substring(0, 8).toUpperCase()}.`,
        });

      } catch (error) {
        console.error("Error adding participants: ", error);
        toast({
          title: "Import Error",
          description: "Could not save participants to the database.",
          variant: "destructive"
        });
      }
    } else {
      toast({
        title: "No New Participants",
        description: "The imported participants are already in the raffle.",
      });
    }
  };

  const handleLogoChange = (file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const newUrl = e.target?.result as string;
      setLogoUrl(newUrl);
      toast({
        title: "Logo Updated",
        description: "The new logo has been applied.",
      });
    };
    reader.readAsDataURL(file);
  };

  const handleLogoClick = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      handleLogoChange(file);
    }
  };

  const handleStartRaffle = () => {
    if (availableParticipants.length === 0) {
      toast({
        title: "Raffle is empty!",
        description: "Please add participants or reset the raffle.",
        variant: "destructive"
      });
      return;
    }
    setSpinHasEnded(false);
    setIsRaffling(true);
    const winnerIndex = secureRandom(availableParticipants.length);
    const pickedWinner = availableParticipants[winnerIndex];
    setWinner(pickedWinner);
  };

  const handleSpinEnd = async () => {
    setSpinHasEnded(true);

    if (winner) {
      const webhookUrl = process.env.NEXT_PUBLIC_WINNER_WEBHOOK_URL;
      if (webhookUrl) {
        try {
          await fetch(webhookUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              name: winner.name,
              last_name: winner.last_name,
              email: winner.email
            })
          });
        } catch (err) {
          console.error('Webhook failed:', err);
          toast({
            title: 'Webhook Error',
            description: 'Failed to send winner notification.',
            variant: 'destructive'
          });
        }
      }
    }
  };

  const handleNextRound = () => {
    setSpinHasEnded(false);
    setIsRaffling(false);
    if (winner) {
      const remaining = availableParticipants.filter(p => p.id !== winner.id);
      setAvailableParticipants(remaining);

      // If that was the last participant, reset available to all for the next major round
      if (remaining.length === 0 && allParticipants.length > 0) {
        toast({
          title: 'Round Complete!',
          description: 'All participants have been chosen. Resetting for a new round.',
        });
        setAvailableParticipants(allParticipants);
      }
    }
    setWinner(null);
  };

  const handleLogoRain = () => {
    if (isRainingLogos) {
      setIsRainingLogos(false);
    } else {
      setIsRainingLogos(true);
      setTimeout(() => setIsRainingLogos(false), 20000); // Stop the rain after 20 seconds
    }
  };

  const handleResetRaffle = () => {
    setAvailableParticipants(allParticipants);
    setWinner(null);
    setIsRaffling(false);
    setSpinHasEnded(false);
    toast({
      title: 'Raffle Reset',
      description: 'All participants are now available for the next round.',
    });
  }

  const participantCount = useMemo(() => allParticipants.length, [allParticipants]);
  const availableCount = useMemo(() => availableParticipants.length, [availableParticipants]);

  const getLoadingMessage = () => {
    if (loading) return "Loading Participants...";
    return "Start Raffle";
  }

  return (
    <>
      <Confetti isCelebrating={spinHasEnded || isRainingLogos} image={logoUrl} />
      <SessionIndicator />
      <ParticipantsList />
      <main className="flex flex-col items-center justify-start min-h-screen w-full p-4 md:p-8 pt-20 md:pt-24 relative">
        <Header
          onParticipantsLoad={handleParticipantsLoad}
          isRaffling={isRaffling}
          onLogoRain={handleLogoRain}
        />

        <div className="w-full max-w-2xl mx-auto flex-grow flex flex-col items-center justify-start gap-8">

          {logoUrl && (
            <button onClick={handleLogoClick} className="cursor-pointer group relative mb-4">
              <Image
                src={logoUrl}
                alt={initialLogo?.description || "Raffle Logo"}
                width={480}
                height={240}
                className="object-contain group-hover:opacity-80 transition-opacity"
                data-ai-hint={initialLogo?.imageHint}
              />
              <div className="absolute inset-0 bg-black/60 rounded-lg flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                <span className="text-white text-sm font-bold">Change Logo</span>
              </div>
            </button>
          )}
          <input
            type="file"
            ref={fileInputRef}
            onChange={handleFileChange}
            accept="image/*"
            className="hidden"
          />

          <SlotMachine
            participants={allParticipants}
            winner={winner}
            isSpinning={isRaffling}
            onSpinEnd={handleSpinEnd}
            loading={loading && allParticipants.length === 0}
            error={error}
          />
          <div className="flex flex-wrap gap-4 items-center justify-center">
            {!isRaffling && !spinHasEnded ? (
              <Button
                onClick={handleStartRaffle}
                disabled={isRaffling || loading || availableParticipants.length === 0 || !!error}
                size="lg"
                className="font-bold text-lg"
                variant={error ? "destructive" : "default"}
              >
                {error ? <ServerCrash className="mr-2 h-5 w-5" /> : <Trophy className="mr-2 h-5 w-5" />}
                {error ? "Connection Failed" : getLoadingMessage()}
              </Button>
            ) : spinHasEnded ? (
              <Button onClick={handleNextRound} size="lg" className="font-bold text-lg">
                Prepare Next Round
              </Button>
            ) : null}

            {availableCount === 0 && participantCount > 0 && !isRaffling && (
              <Button onClick={handleResetRaffle} size="lg" variant="secondary">
                Reset Raffle
              </Button>
            )}

          </div>

          {spinHasEnded && winner && (
            <div className="w-full text-center animate-in fade-in slide-in-from-bottom-4 duration-700">
              <p className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/60">
                {winner.email || winner.display_name}
              </p>
            </div>
          )}
        </div>

        <footer className="text-center text-foreground/80 mt-8">
          <p>Total Participants: {participantCount} | Available this round: {availableCount}</p>
        </footer>
      </main>
    </>
  );
}
